name: buildkite-gcp-scaler
description: buildkite-gcp-scaler build pipeline
steps:
  - label: ":golang:"
    key: "build"
    command: ".buildkite/steps/build"
    agents:
      queue: kubernetes # Switch to Kubernetes queue
    plugins:
    - kubernetes:
        podSpecPatch:
          containers:
          - image: us-central1-docker.pkg.dev/bluecore-ops/ops/agent-stack-k8s:v15.0.3
            name: container-0