#!/usr/bin/env bash

set -eu

trap 'kill $(jobs -p); wait' SIGINT SIGTERM

echo "--- :key: Setting up SSH agent"
ssh:agent() {
    [[ -S /root/.ssh/ssh-agent.sock ]] || ssh-agent -a ~/.ssh/ssh-agent.sock
    export SSH_AUTH_SOCK=/root/.ssh/ssh-agent.sock
    ssh-add
}

ssh:agent

echo "--- :docker: Building and pushing Docker image"
export DOCKER_BUILDKIT=1
export GIT_SHORT_HASH="$(echo $BUILDKITE_COMMIT|cut -c1-7)"

# Build and push Docker image
make docker-push

echo "--- :white_check_mark: Build complete"
echo "Image: us-central1-docker.pkg.dev/bluecore-ops/ops/buildkite-gcp-autoscaler:${GIT_SHORT_HASH}"
